services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    # network_mode: host
    ports:
      - '8000:8000'
    depends_on:
      - postgres
    command: uvicorn main:app --host 0.0.0.0 
  
  postgres:
    image: postgres:alpine
    restart: always
    ports:
      - '5433:5432'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=review
      - POSTGRES_PASSWORD=Tanzo 
  
  


  